Document: iptables-hanxhx
Title: Debian iptables-hanxhx Manual
Author: <insert document author here>
Abstract: This manual describes what iptables-hanxhx is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/iptables-hanxhx/iptables-hanxhx.sgml.gz

Format: postscript
Files: /usr/share/doc/iptables-hanxhx/iptables-hanxhx.ps.gz

Format: text
Files: /usr/share/doc/iptables-hanxhx/iptables-hanxhx.text.gz

Format: HTML
Index: /usr/share/doc/iptables-hanxhx/html/index.html
Files: /usr/share/doc/iptables-hanxhx/html/*.html
